### PR TITLE
Enhance Aesthetic and User Experience [Hacktoberfest] 

### LINKED ISSUE #6: Enhance Aesthetic and User Experience [Hacktoberfest]
The current design of the Math4Python website can be improved to provide a more modern, engaging, and user-friendly experience. This issue proposes the following enhancements:
1. **Use of Modern Fonts:** Replace the outdated `Courier New` with more contemporary fonts like `Poppins` for headers and `Roboto Mono` for code sections.
2. **Navbar:** Make the navigation bar sticky with a shadow effect for better user experience and floating visual appeal.
3. **Background:** Introduce a subtle gradient background to replace the flat color, giving the site a more dynamic look.
4. **Button Styles:** Add hover effects on buttons (like `Run Code`, `Clear Terminal`, etc.) for smoother transitions and interactivity. Include color changes and slight scaling.
5. **Editor and Terminal:** Improve the visual appearance of the editor and terminal by adding rounded corners, borders, and better color contrast.
6. **Card Layout for Features Section:** Reorganize the "Features" section on the homepage using card-style layouts for a cleaner, more modern interface.
7. **Responsive Design:** Ensure that the website remains fully responsive by adjusting the layout (especially the editor and terminal) for smaller screen sizes.

Additionally, please assign me this task as part of Hacktoberfest as I would love to contribute, and kindly add the Hacktoberfest labels to the issue.

### PR DESCRIPTION
**Pull request by mudasirmurtaza**
---
This PR focuses on improving the visual aesthetics of the Math 4 Python website and fixes #6  while ensuring that all existing functionalities remain intact. The following updates were made:

1. **Improved Color Schemes:** 
   - Adjusted background and text colors for various elements to enhance visibility and contrast in both dark and light modes. 
   - Ensured that all text remains readable against its background, particularly for headings, feature boxes, and challenge descriptions.

2. **Box Design Enhancements:**
   - Created visually appealing boxes for features and challenges that adapt to dark and light themes. 
   - The feature boxes now have rounded corners and shadows for a more modern look.

3. **No Functional Changes:**
   - All core functionalities of the website, including the code editor and challeng interactions, remain unchanged and fully operational.
   - The updates were made without altering any JavaScript functionality or HTML structure, aside from a minor edit to the `index.html` file where the text "income M" was removed.e

These improvements enhance the overall user experience by providing a more polished and visually appealing interface, ensuring that users can comfortably navigate and engage with the content regardless of their theme preference.

Feel free to let me know if you need anything else. Also do add the hactober labels.
<h3>Before</h3>

Screenshot 2024-10-12 120713

<h3>After</h3>

Screenshot 2024-10-12 120659

<h3>Dark</h3>

Screenshot 2024-10-12 122016

---

### CODE REVIEW

**Comment by codingkatty** [comment]
Surely looks good and more modern! Still, could you change a nicer font? I think you can find one at google fonts :) the fonts there are quite nice

**Comment by mudasirmurtaza** [comment]
Okay, I'll try to update you by tonight or tomorrow morning.

**Comment by mudasirmurtaza** [comment]
> Surely looks good and more modern! Still, could you change a nicer font? I think you can find one at google fonts :) the fonts there are quite nice

@codingkatty, I am not sure that I am able to get a better font, I am very happy with this new look as it does give a modern look. Can we merge this? maybe someone else can get a better font?

Also, do add the hacktober labels if you decide to merge.

**Comment by codingkatty** [comment]
ok ya sure

**Pull request merged**
